openapi: 3.0.0
info:
  description: |
    This is the API for the cycle test microservice.
  version: "1.0.0"
  title: Cycle Test Microservice
  contact:
    email: terry.chan@hohokusinc.com
    
tags:
  - name: cycleTest
    description: Cycle Test Info

paths:
  /cycletest:
    get:
      tags:
        - cycleTest
      summary: Get the information
      operationId: getCycle
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cycleTestInfo'
        '404':
          description: Item not found
          
    post:
      tags:
        - cycleTest
      summary: Add a new info to the server
      operationId: startCycle
      responses:
        '200':
          description: Ok
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/cycleTestConfig'
        
  /reset:
    get:
      tags:
        - cycleTest
      summary: This is to reset the system and GPIO port
      operationId: resetGpio
      responses:
        '200':
          description: Ok
        '404':
          description: Item not found
    
components:
  schemas:
    cycleTestInfo:
      type: object
      required:
        - cycle_status
      properties:
        cycle_status:
          type: boolean
          example: true
        timestamp:
          type: string
          example: 7/16/2020 16:38
          
    cycleTestConfig:
      type: object
      required:
        - open_activate_time
        - open_retract_time
        - close_activate_time
        - close_retract_time
      properties:
        open_activate_time:
          type: number
          example: 1
        open_retract_time:
          type: number
          example: 2
        close_activate_time:
          type: number
          example: 3
        close_retract_time:
          type: number
          example: 3.5

  requestBodies:
    cycleTestInfo:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/cycleTestInfo'
      required: true
    
    cycleTestConfig:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/cycleTestConfig'