openapi: 3.0.0
info:
  title: Cycle Test Microservice
  description: |
    This is the API for the cycle test microservice.
  contact:
    email: terry.chan@hohokusinc.com
  version: 1.0.0
servers:
- url: /
tags:
- name: cycleTest
  description: Cycle Test Info
paths:
  /cycletest:
    get:
      tags:
      - cycleTest
      summary: Get the information
      operationId: get_info
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/cycleTestInfo'
                x-content-type: application/json
        "404":
          description: Item not found
      x-openapi-router-controller: server.controllers.cycle_test_controller
    post:
      tags:
      - cycleTest
      summary: Add a new info to the server
      operationId: add_info
      requestBody:
        $ref: '#/components/requestBodies/cycleTestInfo'
      responses:
        "200":
          description: Ok
        "405":
          description: Invalid input
      x-openapi-router-controller: server.controllers.cycle_test_controller
components:
  schemas:
    cycleTestInfo:
      required:
      - cycle_number
      - part_number
      type: object
      properties:
        cycle_number:
          type: integer
          example: 1000
        date:
          type: string
          example: 7/16/2020 16:38
        part_number:
          type: string
          example: Hi there
      example:
        date: 7/16/2020 16:38
        cycle_number: 1000
        part_number: Hi there
  requestBodies:
    cycleTestInfo:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/cycleTestInfo'
      required: true

