openapi: 3.0.0
info:
  title: Cycle Test Microservice
  description: |
    This is the API for the cycle test microservice.
  contact:
    email: terry.chan@hohokusinc.com
  version: 1.0.0
servers:
- url: /
tags:
- name: cycleTest
  description: Cycle Test Info
paths:
  /cycletest:
    get:
      tags:
      - cycleTest
      summary: Get the information
      operationId: get_cycle
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cycleTestInfo'
        "404":
          description: Item not found
      x-openapi-router-controller: server.controllers.cycle_test_controller
    post:
      tags:
      - cycleTest
      summary: Add a new info to the server
      operationId: start_cycle
      requestBody:
        $ref: '#/components/requestBodies/cycleTestInfo'
      responses:
        "200":
          description: Ok
        "405":
          description: Invalid input
      x-openapi-router-controller: server.controllers.cycle_test_controller
  /reset:
    get:
      tags:
      - cycleTest
      summary: This is to reset the system and GPIO port
      operationId: reset_gpio
      responses:
        "200":
          description: Ok
        "404":
          description: Item not found
      x-openapi-router-controller: server.controllers.cycle_test_controller
components:
  schemas:
    cycleTestInfo:
      required:
      - cycle_status
      type: object
      properties:
        cycle_status:
          type: boolean
          example: true
        timestamp:
          type: string
          example: 7/16/2020 16:38
      example:
        cycle_status: true
        timestamp: 7/16/2020 16:38
  requestBodies:
    cycleTestInfo:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/cycleTestInfo'
      required: true

